### ISSUE TITLE
package.json dependencies break

### ISSUE THREAD

**Issue by minixxie** [newmsz/node-language-detection#2]
Hi,

Would like to know why the unicode-7.0.0 package is not locked at any version:
"unicode-7.0.0": "x"

In this few days we tried deploy one of our app again but it crashes. We suspect this was caused by a new release of unicode-7.0.0.

```
TypeError: Cannot read property 'forEach' of undefined
langdetect/index.js:249:
        unicode.blocks.forEach(function (unicode_block) {
                UnicodeBlocks.push({
                        name: unicode_block,
                        regex: require('unicode-7.0.0/blocks/' + unicode_block + '/regex')
                });
        });
```

Is it possible to fix it by a new release of langdetect which locks to a specific version of unicode-7.0.0? Your help will be much appreciated!

Simon

**Comment by DavidBruant** [comment]
[This change](https://github.com/mathiasbynens/node-unicode-data/commit/1599c7c53790f8be100369e21f30549d20f74f0d#diff-168726dbe96b3ce427e7fedce31bb0bcL92) on May 28th might be the offender.
See [corresponding Readme change](https://github.com/mathiasbynens/node-unicode-data/commit/1599c7c53790f8be100369e21f30549d20f74f0d#diff-04c6e90faac2675aa89e2176d2eec7d8L74).

[0.5.0](https://github.com/mathiasbynens/unicode-7.0.0/blob/fd849e8d64f2e5a08ddb9f3ba8049e2d8ba77e1f/index.js) built on May 26th still has the string `'blocks'` while [0.6.0](https://github.com/mathiasbynens/unicode-7.0.0/blob/524868e7d90f5fcc4120174ff8832311e4b34132/index.js) built on May 28th doesn't but has `'Block'` instead.
